#TODO - make initialization script that reads from json or similar

class FSW_PARAMS:
    def __init__(self, DT_LOG_S = 5,              # time step between logs
                    DT_HEAT_S = 60,             # time step between checking heater
                    DT_FAST_S = 1,              # time step between fast loop of EKF
                    DT_SLOW_S = 1000,           # time step between slow loop of EKF
                    CHG_LIMIT_V = 4.0,          # voltage to stop charging
                    DIS_LIMIT_V = 3.2,          # voltage to stop discharging
                    TIME_TO_REST_S = 300,       # time to rest between charge/discharge, seconds
                    TEMP_MAX_C =  65,           # above this, go to safe mode
                    TEMP_MIN_C = -10,           # below this, go to safe mode
                    TEMP_HEATER_ON_C  = 10,     # below this, turn heater on
                    TEMP_HEATER_OFF_C = 25,     # above this, turn heater off
                    TEMP_CHG_MAX_C   = 60,      # above this, stop charging
                    TEMP_CHG_UPPER_C = 15,      # above this, charge setpoint is -40 mA
                    TEMP_CHG_LOWER_C = 5,       # above this, charge setpoint is -10 mA
                    TEMP_CHG_MIN_C   = 0,       # below this, stop charging
                    CHG_UPPER_SETPT_MA = -40,   # nominal setpoint
                    CHG_LOWER_SETPT_MA = -10,   # cold setpoint
                    CHG_MIN_SETPT_MA   = -8,    # minimum setpoint
                    CHG_SETPT_DELTA_MA = 0.5,   # if charging current is outside bound, increment potentiometer
                    DIS_SETPT_MA = 40,          # discharge setpoint
                    DIS_SETPT_DELTA_MA = 0.5,   # if discharing current is outside bound, increment ptentiometer
                    DIS_TRANS_MA = 10,          # current level to transition between high and low current mode
                    CHG_VAL_INIT = 9,
                    DIS_VAL_INIT = 76,
                    R_SHUNT_OHMS = [1.0, 1.0, 1.0]):
        self.DT_LOG_S = DT_LOG_S
        self.DT_HEAT_S = DT_HEAT_S
        self.DT_FAST_S = DT_FAST_S
        self.DT_SLOW_S = DT_SLOW_S
        self.CHG_LIMIT_V = CHG_LIMIT_V
        self.DIS_LIMIT_V = DIS_LIMIT_V
        self.TIME_TO_REST_S = TIME_TO_REST_S
        self.TEMP_MAX_C = TEMP_MAX_C
        self.TEMP_MIN_C = TEMP_MIN_C
        self.TEMP_HEATER_ON_C = TEMP_HEATER_ON_C
        self.TEMP_HEATER_OFF_C = TEMP_HEATER_OFF_C
        self.TEMP_CHG_MAX_C = TEMP_CHG_MAX_C
        self.TEMP_CHG_UPPER_C = TEMP_CHG_UPPER_C
        self.TEMP_CHG_LOWER_C = TEMP_CHG_LOWER_C
        self.TEMP_CHG_MIN_C = TEMP_CHG_MIN_C
        self.CHG_UPPER_SETPT_MA = CHG_UPPER_SETPT_MA
        self.CHG_LOWER_SETPT_MA = CHG_LOWER_SETPT_MA
        self.CHG_MIN_SETPT_MA = CHG_MIN_SETPT_MA
        self.CHG_SETPT_DELTA_MA = CHG_SETPT_DELTA_MA
        self.DIS_SETPT_MA = DIS_SETPT_MA
        self.DIS_SETPT_DELTA_MA = DIS_SETPT_DELTA_MA
        self.CHG_VAL_INIT = CHG_VAL_INIT
        self.DIS_VAL_INIT = DIS_VAL_INIT
        self.R_SHUNT_OHMS = R_SHUNT_OHMS
        